name: Docker Build and Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  docker-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t ms-fisio:test .

      - name: Start services with docker-compose
        run: |
          docker-compose up -d

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to start..."
          sleep 60

      - name: Check application health
        run: |
          curl -f http://localhost:8080/actuator/health

      - name: Test login endpoint
        run: |
          curl -X POST http://localhost:8080/api/auth/login \
            -H "Content-Type: application/json" \
            -d '{
              "email": "test@example.com",
              "password": "password123"
            }' \
            --fail

      - name: Show container logs on failure
        if: failure()
        run: |
          echo "Application logs:"
          docker-compose logs app
          echo "Database logs:"
          docker-compose logs postgres

      - name: Cleanup
        if: always()
        run: |
          docker-compose down -v
